[package]
name = "rust-leetcode"
version = "0.1.0"
authors = ["Tuan Vuong <vanhtuan0409@gmail.com>"]
edition = "2018"
default-run = "rust-leetcode"

[[bin]]
name = "generate"
path = "src/generate/main.rs"

[dependencies]
regex = "1"
lazy_static = "1"
